import express from 'express';
import { ObjectId } from 'mongodb';
import { getDB } from '../db_mongodb/db.js';

const router = express.Router();

const PLAN_TYPE_ALIASES = {
  balanced: 'Balanced Diet',
  'balanced diet': 'Balanced Diet',
  'high protein': 'High Protein',
  highprotein: 'High Protein',
  'weight loss': 'Weight Loss',
  weightloss: 'Weight Loss',
  vegetarian: 'Vegetarian',
  keto: 'Keto',
};

const normalizePlanType = (value) => {
  const key = String(value || '').trim().toLowerCase();
  return PLAN_TYPE_ALIASES[key] || 'Balanced Diet';
};

const MEAL_KEYS = ['breakfast', 'lunch', 'dinner', 'snack'];

const sanitizeMealText = (value) => String(value || '').trim();

const sanitizeDays = (days, numDays = 7) => {
  const source = Array.isArray(days)
    ? days
    : Array.from({ length: Number(numDays) || 7 }, (_, i) => ({ day: i + 1 }));

  return source.map((dayObj, idx) => {
    const clean = { day: Number(dayObj?.day) || idx + 1 };

    for (const key of MEAL_KEYS) {
      const text = sanitizeMealText(dayObj?.[key]);
      if (text.length > 0) clean[key] = text;
    }

    return clean;
  });
};

const shuffle = (arr) => {
  const copy = [...arr];
  for (let i = copy.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [copy[i], copy[j]] = [copy[j], copy[i]];
  }
  return copy;
};

const HARD_CODED_TEMPLATES = {
  'Balanced Diet': {
    breakfast: ['Overnight Oats with Berries', 'Greek Yogurt Parfait', 'Avocado Toast with Egg', 'Chia Pudding with Fruits'],
    lunch: ['Grilled Chicken Salad', 'Quinoa Bowl with Veggies', 'Turkey Wrap with Hummus', 'Salmon Rice Bowl'],
    dinner: ['Salmon with Asparagus', 'Lean Beef Stir-Fry', 'Tofu Vegetable Curry', 'Chicken & Sweet Potato'],
    snack: ['Greek Yogurt', 'Mixed Nuts', 'Apple with Peanut Butter', 'Cottage Cheese'],
  },
  'High Protein': {
    breakfast: ['Egg White Omelette', 'Greek Yogurt + Whey + Berries', 'Protein Oats', 'Cottage Cheese Bowl'],
    lunch: ['Chicken Breast & Quinoa', 'Tuna Salad Bowl', 'Turkey Meatballs + Rice', 'Tofu Tempeh Power Bowl'],
    dinner: ['Grilled Salmon + Broccoli', 'Lean Steak + Veg', 'Chicken Stir Fry', 'Baked Cod + Greens'],
    snack: ['Protein Bar', 'Hard-boiled Eggs', 'Edamame', 'Skyr Yogurt'],
  },
  'Weight Loss': {
    breakfast: ['Overnight Oats (Light Portion)', 'Greek Yogurt + Berries', 'Veggie Omelette', 'Green Smoothie Bowl'],
    lunch: ['Grilled Chicken Salad (Light Dressing)', 'Lentil Soup + Side Salad', 'Zucchini Noodle Bowl', 'Tofu Salad Bowl'],
    dinner: ['Baked Fish + Steamed Veg', 'Chicken Veg Soup', 'Turkey Lettuce Wraps', 'Cauliflower Rice Stir-Fry'],
    snack: ['Apple Slices', 'Carrot & Cucumber Sticks', 'Low-fat Yogurt', 'Air-popped Popcorn'],
  },
  Vegetarian: {
    breakfast: ['Overnight Oats with Berries', 'Greek Yogurt Parfait', 'Peanut Butter Banana Toast', 'Tofu Scramble'],
    lunch: ['Hearty Lentil Soup', 'Chickpea Quinoa Salad', 'Veggie Wrap', 'Caprese Salad'],
    dinner: ['Vegetable Curry with Rice', 'Mushroom Pasta', 'Tofu Stir-Fry', 'Stuffed Bell Peppers'],
    snack: ['Mixed Nuts', 'Fruit Salad', 'Hummus with Veg Sticks', 'Yogurt with Seeds'],
  },
  Keto: {
    breakfast: ['Scrambled Eggs with Avocado', 'Keto Chia Pudding', 'Cheese Omelette', 'Smoked Salmon & Egg Plate'],
    lunch: ['Chicken Caesar Salad (No Croutons)', 'Zucchini Noodles with Pesto', 'Egg Salad Lettuce Wraps', 'Tuna Avocado Bowl'],
    dinner: ['Grilled Salmon + Buttered Greens', 'Beef & Broccoli', 'Creamy Garlic Chicken', 'Pork Chops + Roasted Veg'],
    snack: ['Cheese Cubes', 'Almonds', 'Boiled Eggs', 'Celery + Cream Cheese'],
  },
};

const pickForDay = (pool, usedInWeek) => {
  const shuffled = shuffle(pool);
  const pick = shuffled.find((item) => !usedInWeek.has(item)) || shuffled[0] || '';
  if (pick) usedInWeek.add(pick);
  return pick;
};

const buildGeneratedDays = (planType, dayCount = 7) => {
  const category = HARD_CODED_TEMPLATES[planType] || HARD_CODED_TEMPLATES['Balanced Diet'];

  const used = {
    breakfast: new Set(),
    lunch: new Set(),
    dinner: new Set(),
    snack: new Set(),
  };

  return Array.from({ length: dayCount }, (_, i) => ({
    day: i + 1,
    breakfast: pickForDay(category.breakfast, used.breakfast),
    lunch: pickForDay(category.lunch, used.lunch),
    dinner: pickForDay(category.dinner, used.dinner),
    snack: pickForDay(category.snack, used.snack),
  }));
};

const toClientPlan = (doc) => ({
  planId: doc._id.toString(),
  userId: Number(doc.userId),
  name: doc.name || '',
  description: doc.description || '',
  numDays: Number(doc.numDays) || 7,
  days: Array.isArray(doc.days) ? doc.days : [],
  isAutoGenerated: Boolean(doc.isAutoGenerated),
  planType: doc.planType || '',
  createdAt: doc.createdAt,
  updatedAt: doc.updatedAt || null,
});

router.get('/:userId', async (req, res) => {
  try {
    const userId = Number(req.params.userId);
    if (!userId) {
      return res.status(400).json({ success: false, data: [], message: 'Invalid user id.' });
    }

    const db = getDB();
    const collection = db.collection('meal_plans');

    const plans = await collection
      .find({ userId, isDeleted: { $ne: true } })
      .sort({ createdAt: -1 })
      .toArray();

    return res.json({
      success: true,
      data: plans.map(toClientPlan),
      message: '',
    });
  } catch (err) {
    return res.status(500).json({ success: false, data: [], message: err.message });
  }
});

router.post('/', async (req, res) => {
  try {
    const { userId, name, description, numDays, days } = req.body;

    if (!name || !String(name).trim()) {
      return res.status(400).json({
        success: false,
        field: 'name',
        message: 'Plan name is required.',
        data: null,
      });
    }

    const resolvedNumDays = Number(numDays) || 7;
    const sanitizedDays = sanitizeDays(days, resolvedNumDays);

    const doc = {
      userId: Number(userId),
      name: String(name).trim(),
      description: String(description || '').trim(),
      numDays: resolvedNumDays,
      days: sanitizedDays,
      isAutoGenerated: false,
      planType: '',
      isDeleted: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const db = getDB();
    const collection = db.collection('meal_plans');
    const result = await collection.insertOne(doc);

    return res.status(201).json({
      success: true,
      field: null,
      message: 'Meal plan created successfully!',
      data: toClientPlan({ ...doc, _id: result.insertedId }),
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      field: null,
      message: err.message,
      data: null,
    });
  }
});

router.post('/generate', async (req, res) => {
  try {
    const { userId, planType } = req.body;
    const resolvedPlanType = normalizePlanType(planType);

    const db = getDB();

    // Future-ready Mongo template lookup (disabled until templates are populated):
    // const templateCollection = db.collection('meal_templates');
    // const mongoTemplates = await templateCollection.findOne({ planType: resolvedPlanType });

    const generatedDays = buildGeneratedDays(resolvedPlanType, 7);

    const doc = {
      userId: Number(userId),
      name: `${resolvedPlanType} Weekly Plan`,
      description: `Auto-generated ${resolvedPlanType.toLowerCase()} meal plan for 7 days`,
      numDays: 7,
      days: generatedDays,
      isAutoGenerated: true,
      planType: resolvedPlanType,
      isDeleted: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const collection = db.collection('meal_plans');
    const result = await collection.insertOne(doc);

    return res.status(201).json({
      success: true,
      field: null,
      message: 'Meal plan generated successfully!',
      data: toClientPlan({ ...doc, _id: result.insertedId }),
    });
  } catch (err) {
    return res.status(500).json({
      success: false,
      field: null,
      message: err.message,
      data: null,
    });
  }
});

router.put('/:planId', async (req, res) => {
  try {
    const { planId } = req.params;
    const { name, description, numDays, days, planType, isAutoGenerated } = req.body;

    if (!ObjectId.isValid(planId)) {
      return res.status(400).json({ success: false, field: null, message: 'Invalid plan id.', data: null });
    }

    const update = { updatedAt: new Date().toISOString() };

    if (typeof name !== 'undefined') {
      if (!String(name).trim()) {
        return res.status(400).json({ success: false, field: 'name', message: 'Plan name is required.', data: null });
      }
      update.name = String(name).trim();
    }

    if (typeof description !== 'undefined') {
      update.description = String(description || '').trim();
    }

    if (typeof numDays !== 'undefined') {
      update.numDays = Number(numDays) || 7;
    }

    if (typeof days !== 'undefined') {
      update.days = sanitizeDays(days, Number(update.numDays || numDays || 7));
    }

    if (typeof planType !== 'undefined') {
      update.planType = normalizePlanType(planType);
    }

    if (typeof isAutoGenerated !== 'undefined') {
      update.isAutoGenerated = Boolean(isAutoGenerated);
    }

    const db = getDB();
    const collection = db.collection('meal_plans');

    const result = await collection.updateOne(
      { _id: new ObjectId(planId), isDeleted: { $ne: true } },
      { $set: update }
    );

    if (result.matchedCount === 0) {
      return res.status(404).json({ success: false, field: null, message: 'Meal plan not found.', data: null });
    }

    const updatedPlan = await collection.findOne({ _id: new ObjectId(planId) });
    if (!updatedPlan) {
      return res.status(404).json({ success: false, field: null, message: 'Meal plan not found.', data: null });
    }

    return res.json({
      success: true,
      field: null,
      message: 'Meal plan updated successfully!',
      data: toClientPlan(updatedPlan),
    });
  } catch (err) {
    return res.status(500).json({ success: false, field: null, message: err.message, data: null });
  }
});

router.delete('/:planId', async (req, res) => {
  try {
    const { planId } = req.params;

    if (!ObjectId.isValid(planId)) {
      return res.status(400).json({ success: false, message: 'Invalid plan id.' });
    }

    const db = getDB();
    const collection = db.collection('meal_plans');

    const result = await collection.updateOne(
      { _id: new ObjectId(planId), isDeleted: { $ne: true } },
      {
        $set: {
          isDeleted: true,
          deletedAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
      }
    );

    if (result.matchedCount === 0) {
      return res.status(404).json({ success: false, message: 'Meal plan not found.' });
    }

    return res.json({ success: true, message: 'Meal plan deleted' });
  } catch (err) {
    return res.status(500).json({ success: false, message: err.message });
  }
});

export default router;
