import axios from 'axios';
import API_CONFIG from './api_config.js';

const API_URL = `${API_CONFIG}/meal-plans`;

class MealPlan {
  constructor({
    planId = null,
    userId = null,
    name = '',
    description = '',
    numDays = 7,
    days = [],    // [{ day: 1, breakfast: '', lunch: '', dinner: '', snack: '' }]
    isAutoGenerated = false,
    planType = '',    // 'Balanced Diet' | 'High Protein' | 'Weight Loss' | 'Vegetarian' | 'Keto'
    createdAt = null,
    updatedAt = null,
  } = {}) {
    this.planId = planId;
    this.userId = userId;
    this.name = name;
    this.description = description;
    this.numDays = numDays;
    this.days = days;
    this.isAutoGenerated = isAutoGenerated;
    this.planType = planType;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  // Returns a "Sample Day 1:" preview string for the plan card
  getSampleDayPreview() {
    if (!this.days || this.days.length === 0) return null;
    const day = this.days[0];
    const meals = [day.breakfast, day.lunch, day.dinner].filter(Boolean);
    return meals.length > 0
      ? `Sample Day 1:\n${meals.map((m) => `� ${m}`).join('\n')}`
      : 'Sample Day 1:';
  }


  // STATIC VALIDATION METHODS

  // UC #26, #69 � validate meal plan creation
  // @param  {{ name }}
  // @return {{ valid: boolean, field: string|null, message: string }}
  static validatePlan({ name }) {
    if (!name || name.trim().length === 0) {
      return { valid: false, field: 'name', message: 'Plan name is required.' };
    }
    return { valid: true, field: null, message: '' };
  }


  // STATIC / COLLECTION METHODS

  // @param  {MealPlan[]} plans
  // @return {boolean}
  static hasPlans(plans) {
    return plans.length > 0;
  }

  static fromApi(raw) {
    return new MealPlan({
      planId: raw.planId || raw._id || null,
      userId: raw.userId ?? null,
      name: raw.name || '',
      description: raw.description || '',
      numDays: Number(raw.numDays) || 7,
      days: Array.isArray(raw.days) ? raw.days : [],
      isAutoGenerated: Boolean(raw.isAutoGenerated),
      planType: raw.planType || '',
      createdAt: raw.createdAt || null,
      updatedAt: raw.updatedAt || null,
    });
  }


  // DATA ACCESS

  // UC #29, #72 � fetch all meal plans for a user
  // @param  {number} userId
  // @return {Promise<{ success, data, message }>}
  static async fetchAll(userId) {
    try {
      const res = await axios.get(`${API_URL}/${userId}`);
      return {
        success: Boolean(res.data?.success),
        data: Array.isArray(res.data?.data) ? res.data.data.map(MealPlan.fromApi) : [],
        message: res.data?.message || '',
      };
    } catch (err) {
      return {
        success: false,
        data: [],
        message: err.response?.data?.message || 'Unable to load meal plans. Please try again.',
      };
    }
  }

  // UC #26, #69 � create a custom meal plan
  // @param  {number} userId
  // @param  {{ name, description, numDays, days }}
  // @return {Promise<{ success, field, message, data }>}
  static async create(userId, { name, description, numDays, days }) {
    const check = MealPlan.validatePlan({ name });
    if (!check.valid) {
      return { success: false, field: check.field, message: check.message, data: null };
    }

    try {
      const res = await axios.post(`${API_URL}`, {
        userId,
        name,
        description,
        numDays,
        days,
      });

      return {
        success: Boolean(res.data?.success),
        field: res.data?.field ?? null,
        message: res.data?.message || 'Meal plan created successfully!',
        data: res.data?.data ? MealPlan.fromApi(res.data.data) : null,
      };
    } catch (err) {
      return {
        success: false,
        field: err.response?.data?.field ?? null,
        message: err.response?.data?.message || 'Unable to create meal plan. Please try again.',
        data: null,
      };
    }
  }

  // UC #28, #71 � auto-generate a 7-day meal plan
  // @param  {number} userId
  // @param  {{ planType: string }}
  // @return {Promise<{ success, field, message, data }>}
  static async generate(userId, { planType }) {
    try {
      const res = await axios.post(`${API_URL}/generate`, { userId, planType });
      return {
        success: Boolean(res.data?.success),
        field: res.data?.field ?? null,
        message: res.data?.message || 'Meal plan generated successfully!',
        data: res.data?.data ? MealPlan.fromApi(res.data.data) : null,
      };
    } catch (err) {
      return {
        success: false,
        field: err.response?.data?.field ?? null,
        message: err.response?.data?.message || 'Unable to generate meal plan. Please try again.',
        data: null,
      };
    }
  }

  // Future edit support (backend endpoint is ready)
  // @param  {string} planId
  // @param  {{ name?, description?, numDays?, days?, planType? }} fields
  static async update(planId, fields) {
    try {
      const res = await axios.put(`${API_URL}/${planId}`, fields);
      return {
        success: Boolean(res.data?.success),
        field: res.data?.field ?? null,
        message: res.data?.message || 'Meal plan updated successfully!',
        data: res.data?.data ? MealPlan.fromApi(res.data.data) : null,
      };
    } catch (err) {
      return {
        success: false,
        field: err.response?.data?.field ?? null,
        message: err.response?.data?.message || 'Unable to update meal plan. Please try again.',
        data: null,
      };
    }
  }

  // UC #30, #75 � delete a meal plan
  // @param  {string} planId
  // @return {Promise<{ success, message }>}
  static async delete(planId) {
    try {
      const res = await axios.delete(`${API_URL}/${planId}`);
      return {
        success: Boolean(res.data?.success),
        message: res.data?.message || 'Meal plan deleted',
      };
    } catch (err) {
      return {
        success: false,
        message: err.response?.data?.message || 'Unable to delete meal plan. Please try again.',
      };
    }
  }
}

export default MealPlan;
