class MealPlan {
  constructor({
    planId          = null,
    userId          = null,
    name            = '',
    description     = '',
    numDays         = 7,
    days            = [],    // [{ day: 1, breakfast: '', lunch: '', dinner: '', snack: '' }]
    isAutoGenerated = false,
    planType        = '',    // 'Balanced Diet' | 'High Protein' | 'Weight Loss' | 'Vegetarian'
    createdAt       = null,
  } = {}) {
    this.planId          = planId;
    this.userId          = userId;
    this.name            = name;
    this.description     = description;
    this.numDays         = numDays;
    this.days            = days;
    this.isAutoGenerated = isAutoGenerated;
    this.planType        = planType;
    this.createdAt       = createdAt;
  }

  // Returns a "Sample Day 1:" preview string for the plan card
  getSampleDayPreview() {
    if (!this.days || this.days.length === 0) return null;
    const day   = this.days[0];
    const meals = [day.breakfast, day.lunch, day.dinner].filter(Boolean);
    return meals.length > 0
      ? `Sample Day 1:\n${meals.map((m) => `• ${m}`).join('\n')}`
      : 'Sample Day 1:';
  }


  // STATIC VALIDATION METHODS

  // UC #26, #69 — validate meal plan creation
  // @param  {{ name }}
  // @return {{ valid: boolean, field: string|null, message: string }}
  static validatePlan({ name }) {
    if (!name || name.trim().length === 0) {
      return { valid: false, field: 'name', message: 'Plan name is required.' };
    }
    return { valid: true, field: null, message: '' };
  }


  // STATIC / COLLECTION METHODS

  // @param  {MealPlan[]} plans
  // @return {boolean}
  static hasPlans(plans) {
    return plans.length > 0;
  }


  // DATA ACCESS
  // Replace w API calls
  /*
    static async fetchAll(userId) {
      const res = await axios.get(`${API_URL}/meal-plans/${userId}`);
      return res.data.map((r) => new MealPlan(r));
    }

    static async create(userId, fields) {
      const res = await axios.post(`${API_URL}/meal-plans`, { userId, ...fields });
      return res.data;
    }

    static async generate(userId, { planType }) {
      const res = await axios.post(`${API_URL}/meal-plans/generate`, { userId, planType });
      return res.data;
    }

    static async delete(planId) {
      const res = await axios.delete(`${API_URL}/meal-plans/${planId}`);
      return res.data;
    }
  */

  // UC #29, #72 — fetch all meal plans for a user
  // @param  {number} userId
  // @return {Promise<{ success, data, message }>}
  static async fetchAll(userId) {
    return { success: true, data: [], message: '' };
  }

  // UC #26, #69 — create a custom meal plan
  // @param  {number} userId
  // @param  {{ name, description, numDays, days }}
  // @return {Promise<{ success, field, message, data }>}
  static async create(userId, { name, description, numDays, days }) {
    const check = MealPlan.validatePlan({ name });
    if (!check.valid) {
      return { success: false, field: check.field, message: check.message, data: null };
    }

    const resolvedDays = days && days.length > 0
      ? days
      : Array.from({ length: numDays || 7 }, (_, i) => ({
          day: i + 1, breakfast: '', lunch: '', dinner: '', snack: '',
        }));

    const plan = new MealPlan({
      planId:          Date.now(),
      userId,
      name:            name.trim(),
      description:     description || '',
      numDays:         numDays || 7,
      days:            resolvedDays,
      isAutoGenerated: false,
      createdAt:       new Date().toISOString(),
    });

    return {
      success: true,
      field:   null,
      message: 'Meal plan created successfully!',
      data:    plan,
    };
  }

  // UC #28, #71 — auto-generate a 7-day meal plan
  // @param  {number} userId
  // @param  {{ planType: string }}
  // @return {Promise<{ success, field, message, data }>}
  static async generate(userId, { planType }) {
    const templates = {
      'Balanced Diet': [
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Grilled Chicken Salad',     dinner: 'Salmon with Asparagus',         snack: 'Greek Yogurt' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Hearty Lentil Soup',         dinner: 'Vegetable Curry with Rice',      snack: 'Mixed Nuts' },
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Grilled Chicken Salad',      dinner: 'Salmon with Asparagus',          snack: 'Apple' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Vegetable Curry with Rice',  dinner: 'Hearty Lentil Soup',             snack: 'Greek Yogurt' },
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Grilled Chicken Salad',      dinner: 'Vegetable Curry with Rice',      snack: 'Banana' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Hearty Lentil Soup',         dinner: 'Salmon with Asparagus',          snack: 'Mixed Nuts' },
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Grilled Chicken Salad',      dinner: 'Vegetable Curry with Rice',      snack: 'Apple' },
      ],
      'High Protein': [
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Grilled Chicken Salad',      dinner: 'Salmon with Asparagus',          snack: 'Protein Bar' },
        { breakfast: 'Scrambled Eggs & Toast',       lunch: 'Chicken Breast & Quinoa',    dinner: 'Grilled Chicken Salad',          snack: 'Cottage Cheese' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Salmon with Asparagus',      dinner: 'Chicken Breast & Sweet Potato',  snack: 'Hard-boiled Eggs' },
        { breakfast: 'Protein Pancakes',             lunch: 'Grilled Chicken Salad',      dinner: 'Salmon with Asparagus',          snack: 'Greek Yogurt' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Chicken Breast & Quinoa',    dinner: 'Grilled Chicken Salad',          snack: 'Protein Bar' },
        { breakfast: 'Scrambled Eggs & Toast',       lunch: 'Salmon with Asparagus',      dinner: 'Chicken Breast & Sweet Potato',  snack: 'Cottage Cheese' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Grilled Chicken Salad',      dinner: 'Salmon with Asparagus',          snack: 'Mixed Nuts' },
      ],
      'Weight Loss': [
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Hearty Lentil Soup',         dinner: 'Grilled Chicken Salad',          snack: 'Apple' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Grilled Chicken Salad',       dinner: 'Vegetable Curry with Rice',      snack: 'Cucumber slices' },
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Hearty Lentil Soup',          dinner: 'Salmon with Asparagus',          snack: 'Mixed Nuts' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Grilled Chicken Salad',       dinner: 'Hearty Lentil Soup',             snack: 'Orange' },
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Vegetable Curry with Rice',   dinner: 'Grilled Chicken Salad',          snack: 'Apple' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Hearty Lentil Soup',          dinner: 'Salmon with Asparagus',          snack: 'Banana' },
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Grilled Chicken Salad',       dinner: 'Vegetable Curry with Rice',      snack: 'Mixed Nuts' },
      ],
      'Vegetarian': [
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Greek Yogurt Parfait',        dinner: 'Vegetable Curry with Rice',      snack: 'Mixed Berries' },
        { breakfast: 'Avocado Toast',                lunch: 'Hearty Lentil Soup',          dinner: 'Veggie Stir Fry with Tofu',      snack: 'Apple' },
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Caprese Salad',               dinner: 'Vegetable Curry with Rice',      snack: 'Greek Yogurt' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Hearty Lentil Soup',          dinner: 'Mushroom Pasta',                 snack: 'Banana' },
        { breakfast: 'Overnight Oats with Berries',  lunch: 'Veggie Wrap',                 dinner: 'Vegetable Curry with Rice',      snack: 'Mixed Nuts' },
        { breakfast: 'Avocado Toast',                lunch: 'Hearty Lentil Soup',          dinner: 'Caprese Salad with Bread',       snack: 'Orange' },
        { breakfast: 'Greek Yogurt Parfait',         lunch: 'Veggie Stir Fry with Tofu',   dinner: 'Vegetable Curry with Rice',      snack: 'Apple' },
      ],
    };

    const template = templates[planType] || templates['Balanced Diet'];
    const days     = template.map((meals, i) => ({ day: i + 1, ...meals }));

    const plan = new MealPlan({
      planId:          Date.now(),
      userId,
      name:            `${planType || 'Balanced'} Weekly Plan`,
      description:     `Auto-generated ${(planType || 'balanced').toLowerCase()} meal plan for 7 days`,
      numDays:         7,
      days,
      isAutoGenerated: true,
      planType:        planType || 'Balanced Diet',
      createdAt:       new Date().toISOString(),
    });

    return {
      success: true,
      field:   null,
      message: 'Meal plan generated successfully!',
      data:    plan,
    };
  }

  // UC #30, #75 — delete a meal plan
  // @param  {number} planId
  // @return {Promise<{ success, message }>}
  static async delete(planId) {
    return { success: true, message: 'Meal plan deleted' };
  }
}

export default MealPlan;
