// MealPlansScreen.jsx
// Free:    UC #26 Create, #28 Auto-Generate, #29 View, #30 Delete
// Premium: UC #69 Create, #71 Auto-Generate, #72 View, #73 View Details,
//          #74 Edit, #75 Delete
// Sprint 10: UC Sprint10-A Edit Custom Plan, UC Sprint10-B Edit Auto Plan
//
// Sprint 10 changes:
//   - EditCustomMealPlanModal extracted from inline definition (was anti-pattern)
//   - EditAutoMealPlanModal: new — distinct modal for auto-generated plans,
//     lets user change plan type + edit meal slots
//   - MealPlanCard: dispatches onEditCustom vs onEditAuto based on isAutoGenerated
//   - EditCustomMealPlanController + EditAutoMealPlanController wired up
//   - Dine-Out Alternatives block removed from viewingPlan detail view

import React, { useState, useEffect, useCallback } from 'react';
import {
  View, Text, ScrollView, TouchableOpacity, TextInput,
  StyleSheet, StatusBar, ActivityIndicator, Modal, Alert,
  Keyboard, KeyboardAvoidingView, Platform} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import ViewMealPlansController       from '../controller/ViewMealPlansController';
import CreateMealPlanController      from '../controller/CreateMealPlanController';
import GenerateMealPlanController    from '../controller/GenerateMealPlanController';
import DeleteMealPlanController      from '../controller/DeleteMealPlanController';
import EditCustomMealPlanController  from '../controller/EditCustomMealPlanController';
import EditAutoMealPlanController    from '../controller/EditAutoMealPlanController';

const viewCtrl        = new ViewMealPlansController();
const createCtrl      = new CreateMealPlanController();
const generateCtrl    = new GenerateMealPlanController();
const deleteCtrl      = new DeleteMealPlanController();
const editCustomCtrl  = new EditCustomMealPlanController();
const editAutoCtrl    = new EditAutoMealPlanController();

// ── Design Tokens ─────────────────────────────────────────────────────────────
const C = {
  purple:       '#7C3AED',
  purpleLight:  '#EDE9FE',
  dark:         '#111827',
  mid:          '#374151',
  body:         '#4B5563',
  subtle:       '#6B7280',
  white:        '#FFFFFF',
  border:       '#E5E7EB',
  bg:           '#F9FAFB',
  errorText:    '#DC2626',
  successBg:    '#F0FDF4',
  successBorder:'#BBF7D0',
  successText:  '#15803D',
  dangerText:   '#DC2626',
  blue:         '#3B82F6',
  bluePale:     '#EFF6FF',
};

const DAY_OPTIONS = [
  { label: '3 Days',         value: 3  },
  { label: '5 Days',         value: 5  },
  { label: '7 Days (1 Week)',value: 7  },
  { label: '14 Days (2 Weeks)', value: 14 },
];
const PLAN_TYPES  = editAutoCtrl.getPlanTypes();
const MEAL_SLOTS  = ['Breakfast', 'Lunch', 'Dinner', 'Snack'];

// ── NavBar ────────────────────────────────────────────────────────────────────
const NavBar = ({ onMenuPress }) => (
  <View style={nav.bar}>
    <View style={nav.brand}>
      <Text style={nav.icon}>🍴</Text>
      <Text style={nav.brandName}>BiteWise</Text>
    </View>
    <TouchableOpacity onPress={onMenuPress} style={nav.menuBtn}>
      <View style={nav.menuLine} />
      <View style={[nav.menuLine, { width: 18 }]} />
      <View style={nav.menuLine} />
    </TouchableOpacity>
  </View>
);
const nav = StyleSheet.create({
  bar:       { flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingHorizontal:20, paddingVertical:14, backgroundColor:C.white, borderBottomWidth:1, borderBottomColor:C.border },
  brand:     { flexDirection:'row', alignItems:'center', gap:6 },
  icon:      { fontSize:20 },
  brandName: { fontSize:20, fontWeight:'800', color:C.dark, letterSpacing:-0.3 },
  menuBtn:   { padding:6, gap:4, alignItems:'flex-end' },
  menuLine:  { width:22, height:2.5, backgroundColor:C.dark, borderRadius:2 },
});

// ── Banner ────────────────────────────────────────────────────────────────────
const Banner = ({ message }) => {
  if (!message) return null;
  return (
    <View style={bn.wrap}>
      <Text style={bn.icon}>✅</Text>
      <Text style={bn.text}>{message}</Text>
    </View>
  );
};
const bn = StyleSheet.create({
  wrap: { flexDirection:'row', alignItems:'center', gap:10, paddingHorizontal:16, paddingVertical:12, backgroundColor:C.successBg, borderBottomWidth:1, borderBottomColor:C.successBorder },
  icon: { fontSize:16 },
  text: { flex:1, fontSize:14, fontWeight:'500', color:C.successText },
});

// ── ModalSheet ────────────────────────────────────────────────────────────────
const ModalSheet = ({ visible, title, subtitle, onClose, children }) => (
  <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
    <View style={ms.overlay}>
      <View style={ms.sheet}>
        <TouchableOpacity style={ms.closeBtn} onPress={onClose}>
          <Text style={ms.closeIcon}>✕</Text>
        </TouchableOpacity>
        <Text style={ms.title}>{title}</Text>
        {subtitle ? <Text style={ms.subtitle}>{subtitle}</Text> : null}
        {children}
      </View>
    </View>
  </Modal>
);
const ms = StyleSheet.create({
  overlay: { flex:1, backgroundColor:'rgba(0,0,0,0.45)', justifyContent:'center', paddingHorizontal:16 },
  sheet:   { backgroundColor:C.white, borderRadius:16, padding:22, paddingTop:36, maxHeight:'90%' },
  closeBtn:{ position:'absolute', top:12, right:16, padding:4 },
  closeIcon:{ fontSize:16, color:C.subtle },
  title:   { fontSize:16, fontWeight:'700', color:C.dark, textAlign:'center', marginBottom:4 },
  subtitle:{ fontSize:13, color:C.subtle, textAlign:'center', marginBottom:18 },
});

// ── Field ─────────────────────────────────────────────────────────────────────
const Field = ({ label, value, onChangeText, placeholder, multiline, error }) => (
  <View style={fl.wrap}>
    <Text style={fl.label}>{label}</Text>
    <TextInput
      style={[fl.input, multiline && fl.multiline, error && fl.inputError]}
      value={value}
      onChangeText={onChangeText}
      placeholder={placeholder}
      placeholderTextColor={C.subtle}
      multiline={multiline}
      autoCorrect={false}
    />
    {error ? <Text style={fl.error}>{error}</Text> : null}
  </View>
);
const fl = StyleSheet.create({
  wrap:       { marginBottom:12 },
  label:      { fontSize:13, fontWeight:'600', color:C.dark, marginBottom:4 },
  input:      { backgroundColor:C.bg, borderRadius:8, paddingHorizontal:12, paddingVertical:10, fontSize:14, color:C.dark, borderWidth:1, borderColor:C.border },
  multiline:  { minHeight:70, textAlignVertical:'top' },
  inputError: { borderColor:'#FECACA' },
  error:      { fontSize:12, color:C.errorText, marginTop:3 },
});

// ── Shared: day + meal slot editor ───────────────────────────────────────────
const DayMealEditor = ({ days, onUpdateMeal, style }) => (
  <View style={style}>
    {days.map((day, i) => (
      <View key={i}>
        <Text style={sh.dayHeading}>Day {day.day}</Text>
        {MEAL_SLOTS.map((slot) => (
          <View key={slot} style={sh.mealRow}>
            <Text style={sh.mealSlot}>{slot}</Text>
            <TextInput
              style={sh.mealInput}
              value={day[slot.toLowerCase()] || ''}
              onChangeText={(v) => onUpdateMeal(i, slot, v)}
              placeholder={
                slot === 'Breakfast' ? 'e.g., Oatmeal with berries'
                : slot === 'Lunch'   ? 'e.g., Grilled chicken salad'
                : slot === 'Dinner'  ? 'e.g., Salmon with vegetables'
                :                      'e.g., Greek yogurt'
              }
              placeholderTextColor={C.subtle}
              autoCorrect={false}
            />
          </View>
        ))}
      </View>
    ))}
  </View>
);
const sh = StyleSheet.create({
  dayHeading: { fontSize:14, fontWeight:'700', color:C.purple, marginBottom:8, marginTop:4 },
  mealRow:    { marginBottom:8 },
  mealSlot:   { fontSize:12, fontWeight:'600', color:C.dark, marginBottom:3 },
  mealInput:  { backgroundColor:C.bg, borderRadius:6, paddingHorizontal:10, paddingVertical:7, fontSize:13, color:C.dark, borderWidth:1, borderColor:C.border },
});

// ── Shared: day chip picker ───────────────────────────────────────────────────
const DayPicker = ({ numDays, onSelect }) => (
  <View>
    <Text style={dp.label}>Number of Days</Text>
    <View style={dp.row}>
      {DAY_OPTIONS.map((opt) => (
        <TouchableOpacity
          key={opt.value}
          style={[dp.chip, numDays === opt.value && dp.chipActive]}
          onPress={() => onSelect(opt.value)}
          activeOpacity={0.8}
        >
          <Text style={[dp.chipText, numDays === opt.value && dp.chipTextActive]}>
            {opt.label}
          </Text>
        </TouchableOpacity>
      ))}
    </View>
  </View>
);
const dp = StyleSheet.create({
  label:         { fontSize:13, fontWeight:'600', color:C.dark, marginBottom:8 },
  row:           { flexDirection:'row', flexWrap:'wrap', gap:8, marginBottom:16 },
  chip:          { paddingHorizontal:12, paddingVertical:6, borderRadius:20, borderWidth:1, borderColor:C.border, backgroundColor:C.white },
  chipActive:    { backgroundColor:C.purple, borderColor:C.purple },
  chipText:      { fontSize:12, color:C.mid },
  chipTextActive:{ color:C.white, fontWeight:'600' },
});

// ── UC #26, #69 — CREATE MEAL PLAN MODAL ──────────────────────────────────────
const CreatePlanModal = ({ visible, userId, isPremium, onClose, onSuccess }) => {
  const [name,        setName]        = useState('');
  const [description, setDescription] = useState('');
  const [numDays,     setNumDays]     = useState(7);
  const [days,        setDays]        = useState([]);
  const [fieldError,  setFieldError]  = useState('');
  const [isLoading,   setIsLoading]   = useState(false);

  const updateMeal = (dayIdx, slot, value) => {
    setDays((prev) => {
      const updated = [...prev];
      updated[dayIdx] = { ...updated[dayIdx], [slot.toLowerCase()]: value };
      return updated;
    });
  };

  const resetAndClose = () => {
    setName(''); setDescription(''); setNumDays(7); setDays([]); setFieldError('');
    onClose();
  };

  const handleCreate = useCallback(async () => {
    setFieldError('');
    setIsLoading(true);
    const result = await createCtrl.createMealPlan(userId, { name, description, numDays, days });
    setIsLoading(false);
    if (result.success) { resetAndClose(); onSuccess(result.message, result.data); }
    else setFieldError(result.message);
  }, [name, description, numDays, days, userId]);

  useEffect(() => {
    setDays(Array.from({ length: numDays }, (_, i) => ({
      day: i + 1, breakfast: '', lunch: '', dinner: '', snack: '',
    })));
  }, [numDays]);

  return (
    <ModalSheet visible={visible} title="Create Meal Plan" subtitle="Start a new custom meal plan for your week" onClose={resetAndClose}>
      <ScrollView keyboardShouldPersistTaps="handled"
          keyboardDismissMode="on-drag" style={{ maxHeight: 500 }}>
        <Field label="Plan Name" value={name} onChangeText={setName} placeholder="My Weekly Plan" error={fieldError} />
        <Field label="Description (Optional)" value={description} onChangeText={setDescription} placeholder="Describe your meal plan..." multiline />
        <DayPicker numDays={numDays} onSelect={setNumDays} />
        <Text style={{ fontSize:13, color:C.subtle, marginBottom:10 }}>
          Meal Details <Text style={{ color:C.purple }}>(Optional — can be filled later)</Text>
        </Text>
        <DayMealEditor days={days} onUpdateMeal={updateMeal} />
        <TouchableOpacity
          style={[btn.primary, isLoading && btn.disabled]}
          onPress={handleCreate}
          activeOpacity={0.85}
          disabled={isLoading}
        >
          <Text style={btn.primaryText}>{isLoading ? 'Creating...' : '+ Create Plan'}</Text>
        </TouchableOpacity>
      </ScrollView>
    </ModalSheet>
  );
};

// ── UC #28, #71 — AUTO GENERATE MODAL ────────────────────────────────────────
const AutoGenerateModal = ({ visible, userId, onClose, onSuccess }) => {
  const [planType,  setPlanType]  = useState('Balanced Diet');
  const [isLoading, setIsLoading] = useState(false);

  const handleGenerate = useCallback(async () => {
    setIsLoading(true);
    const result = await generateCtrl.generateMealPlan(userId, { planType });
    setIsLoading(false);
    if (result.success) { onClose(); onSuccess(result.message, result.data); }
  }, [planType, userId]);

  return (
    <ModalSheet visible={visible} title="Generate Meal Plan" subtitle="Auto-create a 7-day plan based on your preferences" onClose={onClose}>
      <Text style={{ fontSize:13, fontWeight:'600', color:C.dark, marginBottom:8 }}>Plan Type</Text>
      <View style={{ flexDirection:'row', flexWrap:'wrap', gap:8, marginBottom:20 }}>
        {PLAN_TYPES.map((t) => (
          <TouchableOpacity
            key={t}
            style={[dp.chip, planType === t && dp.chipActive]}
            onPress={() => setPlanType(t)}
            activeOpacity={0.8}
          >
            <Text style={[dp.chipText, planType === t && dp.chipTextActive]}>{t}</Text>
          </TouchableOpacity>
        ))}
      </View>
      <TouchableOpacity
        style={[btn.primary, isLoading && btn.disabled]}
        onPress={handleGenerate}
        activeOpacity={0.85}
        disabled={isLoading}
      >
        <Text style={btn.primaryText}>{isLoading ? 'Generating...' : 'Generate Plan'}</Text>
      </TouchableOpacity>
    </ModalSheet>
  );
};

// ── UC Sprint10-A — EDIT CUSTOM MEAL PLAN MODAL ───────────────────────────────
// Pre-fills all fields from the plan. User can edit name, description,
// number of days, and each individual meal slot.
const EditCustomMealPlanModal = ({ visible, plan, onClose, onSuccess }) => {
  const [name,        setName]        = useState('');
  const [description, setDescription] = useState('');
  const [numDays,     setNumDays]     = useState(7);
  const [days,        setDays]        = useState([]);
  const [fieldError,  setFieldError]  = useState('');
  const [isLoading,   setIsLoading]   = useState(false);

  // Pre-fill from plan when modal opens
  useEffect(() => {
    if (!plan) return;
    setName(plan.name || '');
    setDescription(plan.description || '');
    const n = plan.numDays || 7;
    setNumDays(n);
    setDays(Array.from({ length: n }, (_, i) => {
      const existing = plan.days?.[i] || {};
      return { day: i + 1, breakfast: existing.breakfast || '', lunch: existing.lunch || '', dinner: existing.dinner || '', snack: existing.snack || '' };
    }));
    setFieldError('');
  }, [plan]);

  // Re-build days array when numDays chip changes, preserving existing values
  useEffect(() => {
    setDays((prev) =>
      Array.from({ length: numDays }, (_, i) => {
        const existing = prev[i] || {};
        return { day: i + 1, breakfast: existing.breakfast || '', lunch: existing.lunch || '', dinner: existing.dinner || '', snack: existing.snack || '' };
      })
    );
  }, [numDays]);

  const updateMeal = (dayIdx, slot, value) => {
    setDays((prev) => {
      const updated = [...prev];
      updated[dayIdx] = { ...updated[dayIdx], [slot.toLowerCase()]: value };
      return updated;
    });
  };

  const handleSave = async () => {
    setFieldError('');
    setIsLoading(true);
    const result = await editCustomCtrl.updateCustomPlan(plan.planId, plan.userId, {
      name, description, numDays, days,
    });
    setIsLoading(false);
    if (result.success) {
      onSuccess(result.message, result.data);
      onClose();
    } else if (result.field) {
      setFieldError(result.message);
    } else {
      setFieldError(result.message);
    }
  };

  if (!plan) return null;

  return (
    <ModalSheet
      visible={visible}
      title="Edit Meal Plan"
      subtitle="Update your custom meal plan details"
      onClose={onClose}
    >
      <ScrollView keyboardShouldPersistTaps="handled"
          keyboardDismissMode="on-drag" style={{ maxHeight: 500 }}>
        <Field label="Plan Name *" value={name} onChangeText={setName} placeholder="My Weekly Plan" error={fieldError} />
        <Field label="Description (Optional)" value={description} onChangeText={setDescription} placeholder="Describe your meal plan..." multiline />
        <DayPicker numDays={numDays} onSelect={setNumDays} />
        <Text style={{ fontSize:13, color:C.subtle, marginBottom:10 }}>Meal Details</Text>
        <DayMealEditor days={days} onUpdateMeal={updateMeal} />
        <TouchableOpacity
          style={[btn.primary, isLoading && btn.disabled]}
          onPress={handleSave}
          activeOpacity={0.85}
          disabled={isLoading}
        >
          <Text style={btn.primaryText}>{isLoading ? 'Saving...' : 'Save Changes'}</Text>
        </TouchableOpacity>
      </ScrollView>
    </ModalSheet>
  );
};

// ── UC Sprint10-B — EDIT AUTO-GENERATED MEAL PLAN MODAL ──────────────────────
// Auto plans: user can change the plan type AND edit individual meal slots.
// Plan type badge is shown as context. isAutoGenerated flag is preserved.
const EditAutoMealPlanModal = ({ visible, plan, onClose, onSuccess }) => {
  const [name,        setName]        = useState('');
  const [description, setDescription] = useState('');
  const [planType,    setPlanType]    = useState('Balanced Diet');
  const [days,        setDays]        = useState([]);
  const [fieldError,  setFieldError]  = useState('');
  const [isLoading,   setIsLoading]   = useState(false);

  // Pre-fill when modal opens
  useEffect(() => {
    if (!plan) return;
    setName(plan.name || '');
    setDescription(plan.description || '');
    setPlanType(plan.planType || 'Balanced Diet');
    setDays(Array.from({ length: plan.numDays || 7 }, (_, i) => {
      const existing = plan.days?.[i] || {};
      return { day: i + 1, breakfast: existing.breakfast || '', lunch: existing.lunch || '', dinner: existing.dinner || '', snack: existing.snack || '' };
    }));
    setFieldError('');
  }, [plan]);

  const updateMeal = (dayIdx, slot, value) => {
    setDays((prev) => {
      const updated = [...prev];
      updated[dayIdx] = { ...updated[dayIdx], [slot.toLowerCase()]: value };
      return updated;
    });
  };

  const handleSave = async () => {
    setFieldError('');
    setIsLoading(true);
    const result = await editAutoCtrl.updateAutoMealPlan(plan.planId, plan.userId, {
      name, description, planType, numDays: plan.numDays, days,
    });
    setIsLoading(false);
    if (result.success) {
      onSuccess(result.message, result.data);
      onClose();
    } else {
      setFieldError(result.message);
    }
  };

  if (!plan) return null;

  return (
    <ModalSheet
      visible={visible}
      title="Edit Auto Plan"
      subtitle="Change plan type or adjust individual meal slots"
      onClose={onClose}
    >
      <ScrollView keyboardShouldPersistTaps="handled"
          keyboardDismissMode="on-drag" style={{ maxHeight: 500 }}>

        {/* Auto badge context */}
        <View style={ea.contextRow}>
          <View style={ea.autoBadge}><Text style={ea.autoBadgeTxt}>⚡ Auto-Generated</Text></View>
          <Text style={ea.contextNote}>Changes apply to this plan only</Text>
        </View>

        <Field label="Plan Name *" value={name} onChangeText={setName} placeholder="My Plan" error={fieldError} />
        <Field label="Description (Optional)" value={description} onChangeText={setDescription} placeholder="Describe your meal plan..." multiline />

        {/* Plan type picker */}
        <Text style={{ fontSize:13, fontWeight:'600', color:C.dark, marginBottom:8 }}>Plan Type</Text>
        <View style={{ flexDirection:'row', flexWrap:'wrap', gap:8, marginBottom:16 }}>
          {PLAN_TYPES.map((t) => (
            <TouchableOpacity
              key={t}
              style={[dp.chip, planType === t && dp.chipActive]}
              onPress={() => setPlanType(t)}
              activeOpacity={0.8}
            >
              <Text style={[dp.chipText, planType === t && dp.chipTextActive]}>{t}</Text>
            </TouchableOpacity>
          ))}
        </View>

        <Text style={{ fontSize:13, color:C.subtle, marginBottom:10 }}>Edit Meal Slots</Text>
        <DayMealEditor days={days} onUpdateMeal={updateMeal} />

        <TouchableOpacity
          style={[btn.primary, isLoading && btn.disabled]}
          onPress={handleSave}
          activeOpacity={0.85}
          disabled={isLoading}
        >
          <Text style={btn.primaryText}>{isLoading ? 'Saving...' : 'Save Changes'}</Text>
        </TouchableOpacity>
      </ScrollView>
    </ModalSheet>
  );
};
const ea = StyleSheet.create({
  contextRow:   { flexDirection:'row', alignItems:'center', gap:10, marginBottom:14, padding:10, backgroundColor:C.purpleLight, borderRadius:10 },
  autoBadge:    { backgroundColor:C.purple, borderRadius:20, paddingHorizontal:10, paddingVertical:3 },
  autoBadgeTxt: { fontSize:11, color:C.white, fontWeight:'700' },
  contextNote:  { fontSize:12, color:C.mid, flex:1 },
});

// ── Shared button styles ──────────────────────────────────────────────────────
const btn = StyleSheet.create({
  primary:     { backgroundColor:C.purple, borderRadius:10, paddingVertical:14, alignItems:'center', marginTop:12 },
  disabled:    { opacity:0.6 },
  primaryText: { fontSize:15, fontWeight:'700', color:C.white },
});

// ── Meal Plan Card ────────────────────────────────────────────────────────────
// Dispatches onEditCustom or onEditAuto based on plan.isAutoGenerated
const MealPlanCard = ({ plan, isPremium, onDelete, onViewDetails, onEditCustom, onEditAuto }) => (
  <View style={mc.card}>
    <View style={mc.titleRow}>
      <Text style={mc.title}>{plan.name}</Text>
      {plan.isAutoGenerated && (
        <View style={mc.autoBadge}><Text style={mc.autoBadgeText}>⚡ Auto</Text></View>
      )}
    </View>
    {plan.description ? <Text style={mc.desc}>{plan.description}</Text> : null}
    <View style={mc.metaRow}>
      <Text style={mc.meta}>📅 {plan.numDays} days</Text>
      <Text style={mc.meta}>Created: {plan.createdAt ? new Date(plan.createdAt).toLocaleDateString('en-SG') : 'N/A'}</Text>
    </View>
    {plan.days && plan.days[0] && (
      <View style={mc.preview}>
        <Text style={mc.previewHeading}>Sample Day 1:</Text>
        {[plan.days[0].breakfast, plan.days[0].lunch, plan.days[0].dinner].filter(Boolean).map((m, i) => (
          <Text key={i} style={mc.previewMeal}>• {m}</Text>
        ))}
      </View>
    )}
    <View style={mc.actionRow}>
      <TouchableOpacity style={mc.viewBtn} onPress={() => onViewDetails(plan)} activeOpacity={0.8}>
        <Text style={mc.viewBtnText}>View Details</Text>
      </TouchableOpacity>
      {/* Sprint10-A / Sprint10-B: Edit — Premium only, dispatches correct modal */}
      {isPremium && (
        <TouchableOpacity
          style={mc.editBtn}
          onPress={() => plan.isAutoGenerated ? onEditAuto(plan) : onEditCustom(plan)}
          activeOpacity={0.8}
        >
          <Text style={mc.editBtnText}>✏️ Edit</Text>
        </TouchableOpacity>
      )}
      <TouchableOpacity style={mc.deleteBtn} onPress={() => onDelete(plan.planId)} activeOpacity={0.8}>
        <Text style={mc.deleteBtnText}>🗑 Delete</Text>
      </TouchableOpacity>
    </View>
  </View>
);
const mc = StyleSheet.create({
  card:          { backgroundColor:C.white, borderRadius:14, padding:16, marginBottom:12, borderWidth:1, borderColor:C.border },
  titleRow:      { flexDirection:'row', alignItems:'center', gap:8, marginBottom:4 },
  title:         { fontSize:16, fontWeight:'700', color:C.dark, flex:1 },
  autoBadge:     { backgroundColor:C.purpleLight, borderRadius:20, paddingHorizontal:8, paddingVertical:3 },
  autoBadgeText: { fontSize:11, color:C.purple, fontWeight:'600' },
  desc:          { fontSize:13, color:C.subtle, marginBottom:6 },
  metaRow:       { flexDirection:'row', gap:16, marginBottom:10 },
  meta:          { fontSize:12, color:C.subtle },
  preview:       { marginBottom:12 },
  previewHeading:{ fontSize:13, fontWeight:'700', color:C.dark, marginBottom:4 },
  previewMeal:   { fontSize:12, color:C.purple, marginBottom:2 },
  actionRow:     { flexDirection:'row', gap:8, alignItems:'center' },
  viewBtn:       { borderWidth:1, borderColor:C.border, borderRadius:8, paddingVertical:8, paddingHorizontal:14 },
  viewBtnText:   { fontSize:13, color:C.mid, fontWeight:'500' },
  editBtn:       { borderRadius:8, paddingVertical:8, paddingHorizontal:10 },
  editBtnText:   { fontSize:13, color:C.purple, fontWeight:'600' },
  deleteBtn:     { marginLeft:'auto' },
  deleteBtnText: { fontSize:13, color:C.dangerText, fontWeight:'600' },
});

// ── Main Screen ───────────────────────────────────────────────────────────────
const MealPlansScreen = ({ navigation, route }) => {
  const user      = route?.params?.user || null;
  const isPremium = user?.membershipPlanId === 2 || user?.role === 'premium';

  const [plans,           setPlans]          = useState([]);
  const [isLoading,       setIsLoading]      = useState(true);
  const [banner,          setBanner]         = useState('');
  const [showCreate,      setShowCreate]     = useState(false);
  const [showGenerate,    setShowGenerate]   = useState(false);
  const [viewingPlan,     setViewingPlan]    = useState(null);
  const [editingCustom,   setEditingCustom]  = useState(null);  // Sprint10-A
  const [editingAuto,     setEditingAuto]    = useState(null);  // Sprint10-B

  useEffect(() => {
    viewCtrl.fetchMealPlans(user?.userId).then((result) => {
      if (result.success) setPlans(result.data);
      setIsLoading(false);
    });
  }, []);

  const showBanner = (msg) => {
    setBanner(msg);
    setTimeout(() => setBanner(''), 4000);
  };

  const handlePlanAdded = useCallback((message, plan) => {
    setPlans((prev) => [...prev, plan]);
    showBanner(message);
  }, []);

  // UC Sprint10-A: after edit success, update the plan in list
  const handleCustomEditSuccess = useCallback((msg, updatedPlan) => {
    if (updatedPlan) {
      setPlans((prev) =>
        prev.map((p) => (p.planId === updatedPlan.planId ? updatedPlan : p))
      );
    } else {
      viewCtrl.fetchMealPlans(user?.userId).then((r) => { if (r.success) setPlans(r.data); });
    }
    showBanner(msg);
  }, [user?.userId]);

  // UC Sprint10-B: after edit success, update the plan in list
  const handleAutoEditSuccess = useCallback((msg, updatedPlan) => {
    if (updatedPlan) {
      setPlans((prev) =>
        prev.map((p) => (p.planId === updatedPlan.planId ? updatedPlan : p))
      );
    } else {
      viewCtrl.fetchMealPlans(user?.userId).then((r) => { if (r.success) setPlans(r.data); });
    }
    showBanner(msg);
  }, [user?.userId]);

  // UC #30, #75 — delete
  const handleDelete = useCallback((planId) => {
    Alert.alert('Delete Meal Plan', 'This will permanently delete this meal plan.', [
      { text: 'Cancel', style: 'cancel' },
      {
        text: 'Delete', style: 'destructive',
        onPress: async () => {
          const result = await deleteCtrl.deleteMealPlan(planId);
          if (result.success) {
            setPlans((prev) => prev.filter((p) => p.planId !== planId));
            showBanner('Meal plan deleted.');
          }
        },
      },
    ]);
  }, []);

  // UC #73 — view plan detail
  if (viewingPlan) {
    return (
      <SafeAreaView style={styles.safe}>
        <NavBar onMenuPress={() => navigation.navigate('AccountSettingsScreen', { user })} />
        <ScrollView contentContainerStyle={styles.list}
          keyboardShouldPersistTaps="handled"
          keyboardDismissMode="on-drag"
        >
          <TouchableOpacity onPress={() => setViewingPlan(null)} style={{ paddingVertical: 14 }}>
            <Text style={{ fontSize:14, color:C.mid, fontWeight:'500' }}>← Back to Meal Plans</Text>
          </TouchableOpacity>
          <Text style={styles.pageTitle}>{viewingPlan.name}</Text>
          {viewingPlan.description
            ? <Text style={{ fontSize:13, color:C.subtle, marginBottom:14 }}>{viewingPlan.description}</Text>
            : null}
          {viewingPlan.days.map((day) => (
            <View key={day.day} style={{ backgroundColor:C.white, borderRadius:12, padding:14, marginBottom:10, borderWidth:1, borderColor:C.border }}>
              <Text style={{ fontSize:14, fontWeight:'700', color:C.purple, marginBottom:8 }}>Day {day.day}</Text>
              {MEAL_SLOTS.map((slot) => day[slot.toLowerCase()] ? (
                <View key={slot} style={{ marginBottom:6 }}>
                  <Text style={{ fontSize:12, fontWeight:'600', color:C.mid }}>{slot}</Text>
                  <Text style={{ fontSize:13, color:C.dark }}>{day[slot.toLowerCase()]}</Text>
                </View>
              ) : null)}
            </View>
          ))}
        </ScrollView>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.safe}>
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={{ flex: 1 }}
      >
      <StatusBar barStyle="dark-content" backgroundColor={C.white} />
      <NavBar onMenuPress={() => navigation.navigate('AccountSettingsScreen', { user })} />
      <Banner message={banner} />

      {/* UC #26, #69 — Create */}
      <CreatePlanModal
        visible={showCreate}
        userId={user?.userId}
        isPremium={isPremium}
        onClose={() => setShowCreate(false)}
        onSuccess={handlePlanAdded}
      />

      {/* UC #28, #71 — Auto Generate */}
      <AutoGenerateModal
        visible={showGenerate}
        userId={user?.userId}
        onClose={() => setShowGenerate(false)}
        onSuccess={handlePlanAdded}
      />

      {/* UC Sprint10-A — Edit Custom */}
      <EditCustomMealPlanModal
        visible={!!editingCustom}
        plan={editingCustom}
        onClose={() => setEditingCustom(null)}
        onSuccess={handleCustomEditSuccess}
      />

      {/* UC Sprint10-B — Edit Auto */}
      <EditAutoMealPlanModal
        visible={!!editingAuto}
        plan={editingAuto}
        onClose={() => setEditingAuto(null)}
        onSuccess={handleAutoEditSuccess}
      />

      <ScrollView contentContainerStyle={styles.list} showsVerticalScrollIndicator={false}
          keyboardShouldPersistTaps="handled"
          keyboardDismissMode="on-drag"
        >
        <Text style={styles.pageTitle}>Meal Plans</Text>
        <Text style={styles.pageSubtitle}>Create and manage your weekly meal plans</Text>

        <View style={styles.actionRow}>
          <TouchableOpacity style={styles.autoBtn} onPress={() => setShowGenerate(true)} activeOpacity={0.85}>
            <Text style={styles.autoIcon}>⚡</Text>
            <Text style={styles.autoBtnText}>Auto Generate</Text>
          </TouchableOpacity>
          <TouchableOpacity style={styles.createBtn} onPress={() => setShowCreate(true)} activeOpacity={0.85}>
            <Text style={styles.createBtnText}>+ Create Plan</Text>
          </TouchableOpacity>
        </View>

        {isLoading ? (
          <ActivityIndicator size="large" color={C.purple} style={{ marginTop: 40 }} />
        ) : plans.length === 0 ? (
          <View style={styles.emptyState}>
            <Text style={styles.emptyIcon}>📅</Text>
            <Text style={styles.emptyTitle}>No Meal Plans Yet</Text>
            <Text style={styles.emptyBody}>Create your first meal plan to start organising your weekly meals</Text>
            <View style={styles.emptyBtnRow}>
              <TouchableOpacity style={styles.autoBtn} onPress={() => setShowGenerate(true)} activeOpacity={0.85}>
                <Text style={styles.autoIcon}>⚡</Text>
                <Text style={styles.autoBtnText}>Auto Generate</Text>
              </TouchableOpacity>
              <TouchableOpacity style={styles.createBtn} onPress={() => setShowCreate(true)} activeOpacity={0.85}>
                <Text style={styles.createBtnText}>+ Create Plan</Text>
              </TouchableOpacity>
            </View>
          </View>
        ) : (
          plans.map((plan) => (
            <MealPlanCard
              key={plan.planId}
              plan={plan}
              isPremium={isPremium}
              onDelete={handleDelete}
              onViewDetails={setViewingPlan}
              onEditCustom={setEditingCustom}
              onEditAuto={setEditingAuto}
            />
          ))
        )}
      </ScrollView>
          </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  safe:         { flex:1, backgroundColor:C.bg },
  list: { flexGrow: 1, paddingHorizontal:16, paddingBottom:32 },
  pageTitle:    { fontSize:26, fontWeight:'800', color:C.dark, letterSpacing:-0.3, paddingTop:20, marginBottom:4 },
  pageSubtitle: { fontSize:13, color:C.subtle, marginBottom:16 },
  actionRow:    { flexDirection:'row', gap:10, marginBottom:16 },
  autoBtn:      { flexDirection:'row', alignItems:'center', gap:4, borderWidth:1, borderColor:C.border, borderRadius:8, paddingVertical:10, paddingHorizontal:14, backgroundColor:C.white },
  autoIcon:     { fontSize:14, color:C.purple },
  autoBtnText:  { fontSize:13, fontWeight:'600', color:C.dark },
  createBtn:    { flexDirection:'row', alignItems:'center', backgroundColor:C.purple, borderRadius:8, paddingVertical:10, paddingHorizontal:16 },
  createBtnText:{ fontSize:13, fontWeight:'700', color:C.white },
  emptyState:   { backgroundColor:C.white, borderRadius:14, padding:32, alignItems:'center', borderWidth:1, borderColor:C.border },
  emptyIcon:    { fontSize:48, marginBottom:12 },
  emptyTitle:   { fontSize:18, fontWeight:'700', color:C.dark, marginBottom:6 },
  emptyBody:    { fontSize:13, color:C.subtle, textAlign:'center', lineHeight:20, marginBottom:20 },
  emptyBtnRow:  { flexDirection:'row', gap:10 },
});

export default MealPlansScreen;
