// EditAutoMealPlanController.js — Sprint 10
// UC Sprint10-B: Premium User – Edit Auto-Generated Meal Plan
//
// Normal Flow:
//   1. EditAutoMealPlanModal submits fields → boundary calls updateAutoMealPlan()
//   2. Controller delegates to MealPlan.updateAutoGeneratedPlan(planId, userId, fields)
//   3. Returns { success, field, message, data } to boundary
//   4. Boundary updates plan card in list, closes modal, shows success banner
//
// Key difference from custom plan edit:
//   - planType field is included (user may change the diet category)
//   - isAutoGenerated flag preserved as true on the returned plan
//
// Alt Flow 1: name empty → { success: false, field: 'name', message }
// Alt Flow 2: unexpected error → { success: false, message }
// Premium User only

import MealPlan from '../entity/MealPlan';

const PLAN_TYPES = ['Balanced Diet', 'High Protein', 'Weight Loss', 'Vegetarian', 'Keto'];

class EditAutoMealPlanController {
  constructor() {}

  async _safe(fn) {
    try {
      return await fn();
    } catch (e) {
      console.error('[EditAutoMealPlanController]', e);
      return { success: false, field: null, message: 'Unable to update meal plan. Please try again.', data: null };
    }
  }

  // Returns the available plan type options for the dropdown in the boundary.
  // @return {string[]}
  getPlanTypes() {
    return PLAN_TYPES;
  }

  // @param  {string|number} planId
  // @param  {string|number} userId
  // @param  {{ name, description, planType, numDays, days[] }} fields
  // @return {Promise<{ success, field, message, data }>}
  async updateAutoMealPlan(planId, userId, fields) {
    return this._safe(async () => {
      if (!planId || !userId) {
        return { success: false, field: null, message: 'Invalid plan or user.', data: null };
      }
      return MealPlan.updateAutoGeneratedPlan(planId, userId, fields);
    });
  }
}

export default EditAutoMealPlanController;
